// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.4
// source: pkg/client/serverpb/api.proto

package serverpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Transaction         string                 `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Mode                string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	SkipPreflight       bool                   `protobuf:"varint,3,opt,name=skipPreflight,proto3" json:"skipPreflight,omitempty"`
	PreflightCommitment string                 `protobuf:"bytes,4,opt,name=preflightCommitment,proto3" json:"preflightCommitment,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_pkg_client_serverpb_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_client_serverpb_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_pkg_client_serverpb_api_proto_rawDescGZIP(), []int{0}
}

func (x *SendRequest) GetTransaction() string {
	if x != nil {
		return x.Transaction
	}
	return ""
}

func (x *SendRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *SendRequest) GetSkipPreflight() bool {
	if x != nil {
		return x.SkipPreflight
	}
	return false
}

func (x *SendRequest) GetPreflightCommitment() string {
	if x != nil {
		return x.PreflightCommitment
	}
	return ""
}

type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     string                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_pkg_client_serverpb_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_client_serverpb_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_pkg_client_serverpb_api_proto_rawDescGZIP(), []int{1}
}

func (x *SendResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_pkg_client_serverpb_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_client_serverpb_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_pkg_client_serverpb_api_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_pkg_client_serverpb_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_client_serverpb_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_pkg_client_serverpb_api_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_pkg_client_serverpb_api_proto protoreflect.FileDescriptor

const file_pkg_client_serverpb_api_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/client/serverpb/api.proto\x12\bserverpb\"\x9b\x01\n" +
	"\vSendRequest\x12 \n" +
	"\vtransaction\x18\x01 \x01(\tR\vtransaction\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12$\n" +
	"\rskipPreflight\x18\x03 \x01(\bR\rskipPreflight\x120\n" +
	"\x13preflightCommitment\x18\x04 \x01(\tR\x13preflightCommitment\",\n" +
	"\fSendResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\tR\tsignature\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\x8e\x01\n" +
	"\x06Server\x12B\n" +
	"\x0fSendTransaction\x12\x15.serverpb.SendRequest\x1a\x16.serverpb.SendResponse\"\x00\x12@\n" +
	"\tGetHealth\x12\x17.serverpb.HealthRequest\x1a\x18.serverpb.HealthResponse\"\x00B#Z!sol-speedtest/pkg/client/serverpbb\x06proto3"

var (
	file_pkg_client_serverpb_api_proto_rawDescOnce sync.Once
	file_pkg_client_serverpb_api_proto_rawDescData []byte
)

func file_pkg_client_serverpb_api_proto_rawDescGZIP() []byte {
	file_pkg_client_serverpb_api_proto_rawDescOnce.Do(func() {
		file_pkg_client_serverpb_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_client_serverpb_api_proto_rawDesc), len(file_pkg_client_serverpb_api_proto_rawDesc)))
	})
	return file_pkg_client_serverpb_api_proto_rawDescData
}

var file_pkg_client_serverpb_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_client_serverpb_api_proto_goTypes = []any{
	(*SendRequest)(nil),    // 0: serverpb.SendRequest
	(*SendResponse)(nil),   // 1: serverpb.SendResponse
	(*HealthRequest)(nil),  // 2: serverpb.HealthRequest
	(*HealthResponse)(nil), // 3: serverpb.HealthResponse
}
var file_pkg_client_serverpb_api_proto_depIdxs = []int32{
	0, // 0: serverpb.Server.SendTransaction:input_type -> serverpb.SendRequest
	2, // 1: serverpb.Server.GetHealth:input_type -> serverpb.HealthRequest
	1, // 2: serverpb.Server.SendTransaction:output_type -> serverpb.SendResponse
	3, // 3: serverpb.Server.GetHealth:output_type -> serverpb.HealthResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_client_serverpb_api_proto_init() }
func file_pkg_client_serverpb_api_proto_init() {
	if File_pkg_client_serverpb_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_client_serverpb_api_proto_rawDesc), len(file_pkg_client_serverpb_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_client_serverpb_api_proto_goTypes,
		DependencyIndexes: file_pkg_client_serverpb_api_proto_depIdxs,
		MessageInfos:      file_pkg_client_serverpb_api_proto_msgTypes,
	}.Build()
	File_pkg_client_serverpb_api_proto = out.File
	file_pkg_client_serverpb_api_proto_goTypes = nil
	file_pkg_client_serverpb_api_proto_depIdxs = nil
}
